#ifndef GLOBALDEFINE_H
#define GLOBALDEFINE_H

//#define SOCKET_DEBUG
#define QML_DB_CON "QML_DB_CON"
#define INVALID_ULONGLONG 0xffffffffffffffff

//#define BUILD_COMPANY_DONGNAM
#define BUILD_MODEL_NSWCNSAMD480
#define BUILD_STR_VERSION "1.2.3"

#define EVENT_PAGE_CNT_PER_SCREEN 9
#define EVENT_LIST_CNT_PER_PAGE 26
#define TRENDS_POINT_BUFF_CNT 999999
#define COMM_SEND_TIMEOUT 100
#define COMM_RCV_TIMEOUT 10000
#define PRODUCT_NAME_LENGTH 15

#define SYNC_PORT 10024
#define MONITORING_PORT 10026
#define DSP_COMM_PORT 10020
#define DEVICE_SEARH_PORT 10022
#endif // GLOBALDEFINE_H
