#ifndef GLOBALDEFINE_H
#define GLOBALDEFINE_H

//#define SOCKET_DEBUG
//#define OS_WINDOW
#define QML_DB_CON "QML_DB_CON"
#define INVALID_ULONGLONG 0xffffffffffffffff

//#define BUILD_DONGNAM

#define MODEL "NSWCNSAMD480"
#define VERSION "1.0.0"

#define EVENT_PAGE_CNT_PER_SCREEN 9
#define EVENT_LIST_CNT_PER_PAGE 26
#define TRENDS_POINT_BUFF_CNT 999999
#define COMM_SEND_TIMEOUT 100
#define COMM_RCV_TIMEOUT 10000
#define PRODUCT_NAME_LENGTH 15
#endif // GLOBALDEFINE_H
